### PR TITLE
chore: fix nms & use views instead of owned arrays

### PR DESCRIPTION
**Pull request by Smirkey**
#51

### CODE REVIEW

**Comment by Smirkey** [comment]
Hi @BTOdell I've extended a bit the use of array views and also fixed the python bindings. Overall things are well speed up especially NMS which is really cool !
I'm a bit puzzled by the IoUs functions results (iou/diou/giou...). In all of them a new block is taking a lot of time: `<ndarray::ArrayBase<S,D> as numpy::convert::ToPyArray>::to_pyarray (37.99%) (new)` (cf the benchmarks by codspeed in the profiling tab). 

I've tried a bunch of things but couldn't figure out why things are slowed down there. A theory could be that in the case where our output is significantly bigger than our input (which for ious functions which return a matrix from 2 vectors) it's better to deal with OwneRepr ... do you have any idea ?

**Comment by BTOdell** [comment]
When you pass in an owned ndarray to a function, you give up ownership of that data and the caller won't use it anymore, so when it's converted to a PyArray, the internal data can simply be moved into the PyArray without doing an element-by-element copy. You can see in the new flamegraph, it's called `__memcpy_avx_unaligned_erms` that does the data copy instead of the old code just does a data move with `PyArray::from_owned_array`.

Also, I noticed you added back the `EPS` value to "fix" the divide by zero in the NMS algorithm. I don't think that the `union` value can ever be zero. Can you provide an example when this value would ever be zero?

**Comment by BTOdell** [comment]
To overcome the issue with the element-by-element copying, you could try accepting a CowArray instead of an ArrayView. That way, if the user has an owned array that they won't need after calling the function, they can pass in the owned array to regain the original performance. But if they need the array after the call, then they would pass in a view.

**Comment by BTOdell** [comment]
> Also, I noticed you added back the `EPS` value to "fix" the divide by zero in the NMS algorithm. I don't think that the `union` value can ever be zero. Can you provide an example when this value would ever be zero?

@Smirkey Can you comment on this?

**Comment by Buillaume** [comment]
The zero division errors only come with integer types

**Comment by Smirkey** [comment]
> > Also, I noticed you added back the `EPS` value to "fix" the divide by zero in the NMS algorithm. I don't think that the `union` value can ever be zero. Can you provide an example when this value would ever be zero?
> 
> @Smirkey Can you comment on this?

yeah sure sorry ! I added it back because it broke the test (division by zero errors), but will look further into what you've done for fixing nms later, my goal at first was to get everything working along with the bindings
At a first glance I don't see what was wrong with the NMS implementation nor why your changes fixed it, it might be linked to these zero division errors, do you have more insights on this ?

As for the slow down observed in codspeed benchmarks, it was linked to the fact that I use `to_pyarray` instead of `into_pyarray`, which is the function to use with `OwnedRepr`

**Comment by Smirkey** [comment]
> > Also, I noticed you added back the `EPS` value to "fix" the divide by zero in the NMS algorithm. I don't think that the `union` value can ever be zero. Can you provide an example when this value would ever be zero?
> 
> @Smirkey Can you comment on this?

yeah sure sorry ! I added it back because it broke the test (division by zero errors), but will look further into what you've done for fixing nms later, my goal at first was to get everything working along with the bindings
At a first glance I don't see what was wrong with the NMS implementation nor why your changes fixed it, it might be linked to these zero division errors, do you have more insights on this ?

As for the slow down observed in codspeed benchmarks, it was linked to the fact that I use `to_pyarray` instead of `into_pyarray`, which is the function to use with `OwnedRepr`

**Comment by Smirkey** [comment]
> > Also, I noticed you added back the `EPS` value to "fix" the divide by zero in the NMS algorithm. I don't think that the `union` value can ever be zero. Can you provide an example when this value would ever be zero?
> 
> @Smirkey Can you comment on this?

yeah sure sorry ! I added it back because it broke the test (division by zero errors), but will look further into what you've done for fixing nms later, my goal at first was to get everything working along with the bindings
At a first glance I don't see what was wrong with the NMS implementation nor why your changes fixed it, it might be linked to these zero division errors, do you have more insights on this ?

As for the slow down observed in codspeed benchmarks, it was linked to the fact that I use `to_pyarray` instead of `into_pyarray`, which is the function to use with `OwnedRepr`

**Comment by Smirkey** [comment]
The zero division errors only occur whit integer and usigned integers

**Comment by BTOdell** [comment]
> At a first glance I don't see what was wrong with the NMS implementation nor why your changes fixed it, it might be linked to these zero division errors, do you have more insights on this ?

I believe it's either related to all of the `f64::min` operations you were doing between the area1/2 and the intersection. It was completely messing up the IOU calculation.

Also, I think it's possible that adding the `EPS` value to the denominator could also result in accuracy issues, which is why I've been concerned about it being added back.

**Comment by BTOdell** [comment]
But it looks like everything is passing even with the `EPS` removed! Congrats! 🎉

**Pull request merged**
