### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by BTOdell**

### CODE REVIEW

**Comment by BTOdell** [comment]
I just fixed a bug in the NMS algorithm. The old algorithm implementation was producing results like:

image

and the new implementation is producing results like:

image

**Comment by Smirkey** [comment]
thanks a lot for the changes ! 

I think it won't be practical to handle this in a single PR (moving from owned arrays to views)
I changed the base branch to a dev branch

**Comment by BTOdell** [comment]
I only opened this PR to have as a reference into my fork. I don't plan on making further changes to my fork to fix the CI errors. I encourage you to just use my fork as a reference to make the changes across the entire project. My fork only has made the changes for a few select functions that I needed to use.

**Comment by BTOdell** [comment]
I'd be happy to answer any questions about why I made certain changes. I haven't run any benchmarks on the new code, so for all I know my implementation could be slower than yours. I was going for correctness as top priority.

**Comment by Buillaume** [comment]
you're right ! 
As for speed, using views is the way to go and I believe that it'll bring significant speedups specifically in python
there are automated benchmarks in the CI that will run when the tests will pass. 

Thanks you very much for this work, I'll make the other necessary changes in the feature branch I created

**Comment by Smirkey** [comment]
you're right !
As for speed, using views is the way to go and I believe that it'll bring significant speedups specifically in python
there are automated benchmarks in the CI that will run when the tests will pass.

Thanks you very much for this work, I'll make the other necessary changes in the feature branch I created

**Pull request merged**
